---
- name: Step 1 Generate config.yml and dashboard certificates
  hosts: dashboard
  become: yes
  vars_files:
    - wazuh.yml
  tasks:
    - name: Ensure cert generation dir exists
      file:
        path: /home/{{ ansible_user }}
        state: directory
        mode: '0755'

    - name: Check if root-ca.pem already exists
      stat:
        path: /home/{{ ansible_user }}/wazuh-certificates/root-ca.pem
      register: root_ca_check

    - name: Skip cert generation if root-ca.pem already exists
      debug:
        msg: "Root CA already exists, skipping certificate generation."
      when: root_ca_check.stat.exists

    - name: Generate config.yml from template
      template:
        src: template/config.yml.j2
        dest: /home/{{ ansible_user }}/config.yml
      when: not root_ca_check.stat.exists

#    - name: Download Wazuh certificate tool
#      get_url:
#        url: https://packages.wazuh.com/4.11/wazuh-certs-tool.sh
#        dest: /home/{{ ansible_user }}/wazuh-certs-tool.sh
#        mode: '0755'
#      when: not root_ca_check.stat.exists

    - name: Generate certificates and root-ca
      command: bash ./wazuh-certs-tool.sh -A
      args:
        chdir: /home/{{ ansible_user }}
      when: not root_ca_check.stat.exists

    - name: Archive the generated certificates
      command: tar -cvf wazuh-certificates.tar -C ./wazuh-certificates/ .
      args:
        chdir: /home/{{ ansible_user }}
      when: not root_ca_check.stat.exists

- name: Step 2 Copy root-ca.* to all Wazuh devices (excluding agents and dashboard)
  hosts: wazuh:!agent:!dashboard
  become: yes
  vars_files:
    - wazuh.yml
  tasks:
    - name: delete root cert destination dir if not exist
      file:
        path: /home/{{ ansible_user }}/certs
        state: absent

    - name: delete cert destination dir if not exist
      file:
        path: /home/{{ ansible_user }}/wazuh-certificates
        state: absent

    - name: delete cert.tar destination dir if not exist
      file:
        path: /home/{{ ansible_user }}/wazuh-certificates.tar
        state: absent

    - name: Create cert destination dir if not exist
      file:
        path: /home/{{ ansible_user }}/certs
        state: directory
        mode: '0755'

    - name: Copy root-ca.pem
      copy:
        src: /home/{{ hostvars['dashboard_1']['ansible_user'] }}/wazuh-certificates/root-ca.pem
        dest: /home/{{ ansible_user }}/certs/root-ca.pem
        mode: '0644'
        force: yes

    - name: Copy root-ca.key
      copy:
        src: /home/{{ hostvars['dashboard_1']['ansible_user'] }}/wazuh-certificates/root-ca.key
        dest: /home/{{ ansible_user }}/certs/root-ca.key
        mode: '0600'
        force: yes

    - name: Generate config.yml
      template:
        src: template/config.yml.j2
        dest: /home/{{ ansible_user }}/config.yml

    - name: Remove existing wazuh-certificates directory if present
      file:
        path: /home/{{ ansible_user }}/wazuh-certificates
        state: absent

    - name: Run certificate generation with received root-ca.*
      command: bash /home/{{ ansible_user }}/wazuh-certs-tool.sh -A /home/{{ ansible_user }}/certs/root-ca.pem /home/{{ ansible_user }}/certs/root-ca.key
      args:
        chdir: /home/{{ ansible_user }}

    - name: Archive the generated certificates
      command: tar -cvf wazuh-certificates.tar -C ./wazuh-certificates/ .
      args:
        chdir: /home/{{ ansible_user }}


