all:
  children:
    site_a_server:
      hosts:
        server_a_1:
          ansible_host: 10.10.10.22
          ansible_connection: docker
    site_a_indexer:
      hosts:
        indexer_a_1:
          ansible_host: 10.10.10.21
          ansible_connection: docker
    site_a_agent:
      hosts:
        agent_a_1:
          ansible_host: 10.10.10.23
          ansible_connection: docker
    site_b_indexer:
      hosts:
        indexer_b_1:
          ansible_host: 10.20.20.21
          ansible_connection: docker
    site_b_server:
      hosts:
        server_b_1:
          ansible_host: 10.20.20.22
          ansible_connection: docker
    site_dashboard:
      hosts:
        dashboard_1:
          ansible_host: 10.30.30.112
          ansible_connection: docker

all:
  vars:
    is_test_mode: true
